name: 'Build MBox Plugin'
description: 'Build MBox Plugin by GitHub Actions'
author: 'RyanLeeLY'
inputs:
  token:
    required: true
    description: 'GitHub Token'
outputs:
  build-path:
    description: 'Output build path'
runs:
  using: 'node12'
  main: 'dist/index.js'
